name: 'Terraform PR'
description: 'GitHub Action for adding `terraform plan` output as a PR comment'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  github-token:
    description: "GitHub token for commenting on PRs. Defaults to using 'secrets.GITHUB_TOKEN'"
    required: false
    default: ${{ github.token }}
  apply-branch:
    description: "Branch to run `terraform apply` on. Leave blank to disable auto-apply."
    required: false
    default: ""
  path:
    description: "Path to the Terraform configuration. Defaults to '.' if not specified."
    required: false
    default: "."
  pr-comment-title:
    description: "Custom title for the PR comment. Defaults to '${TF_WORKSPACE}' if not specified."
    required: false
    default: ""
  lock-for-plan:
    description: "Should we use a workspace lock for the `terraform plan`? https://www.terraform.io/language/state/locking"
    required: false
    default: true
  require-formatting:
    description: "Should we require the terraform formatting check?"
    required: false
    default: false
  require-validate:
    description: "Should we require the terraform validate check?"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Terraform Format
      id: fmt
      shell: bash
      run: |
        cd ${{ inputs.path }}
        if terraform fmt -recursive -check; then
          echo "::set-output name=fmt-outcome::success"
        else
          echo "::set-output name=fmt-outcome::failure"
        fi

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        cd ${{ inputs.path }}
        if terraform init; then
          echo "::set-output name=init-outcome::success"
        else
          echo "::set-output name=init-outcome::failure"
        fi

    - name: Terraform Workspace
      id: workspace
      shell: bash
      run: |
        cd ${{ inputs.path }}
        if terraform workspace show; then
          echo "::set-output name=workspace-outcome::success"
        else
          echo "::set-output name=workspace-outcome::failure"
        fi

    - name: Terraform Validate
      id: validate
      shell: bash
      run: |
        cd ${{ inputs.path }}
        if terraform validate -no-color; then
          echo "::set-output name=validate-outcome::success"
        else
          echo "::set-output name=validate-outcome::failure"
        fi

    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        if [[ '${{ github.ref }}' != 'refs/heads/${{ inputs.apply-branch }}' ]]; then
          cd ${{ inputs.path }}
          if terraform plan -no-color -lock=${{ inputs.lock-for-plan }} | tail -c 63535; then
            echo "::set-output name=plan-outcome::success"
          else
            echo "::set-output name=plan-outcome::failure"
          fi
        fi

    - name: Create/Update Comment
      uses: actions/github-script@v4
      env:
        PLAN: "terraform\n\n${{ steps.plan.outputs.stdout }}\n${{ steps.plan.outputs.stderr }}"
        TF_WORKSPACE: "${{ steps.workspace.outputs.stdout }}"
        CUSTOM_TITLE: "${{ inputs.pr-comment-title }}"
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const tag = [
            process.env.CUSTOM_TITLE,
            process.env.TF_WORKSPACE,
          ]
            .filter(s => !!s)
            .join(" ");

          const commentTitle = `### Terraform Status ${tag}`;
          const commentContent = `
          ${commentTitle}
          #### Terraform Format and Style 🖌 \`${{ steps.fmt.outputs.fmt-outcome }}\`
          #### Terraform Validate 📖 \`${{ steps.validate.outputs.validate-outcome }}\`
          #### Terraform Plan 📖 \`${{ steps.plan.outputs.plan-outcome }}\`
          <details>
          <summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>

          Pusher: @${{ github.actor }}
          Action: \`${{ github.event_name }}\`
          `;

          if (!context || !context.issue || !context.issue.number) {
            return;
          }

          const comments = await github.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const githubActionsBotComment = comments.data.find(comment =>
            comment.user.login === 'github-actions[bot]' &&
             comment.body.includes(commentTitle)
          );

          if (commentContent.includes("No changes.")) {
            if (githubActionsBotComment) {
              await github.issues.deleteComment({
                comment_id: githubActionsBotComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            }
          } else {
            if (githubActionsBotComment) {
              await github.issues.updateComment({
                comment_id: githubActionsBotComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentContent,
              })
            } else {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentContent,
              })
            }
          }

    - name: Terraform Validate Status
      shell: bash
      run: |
        if [[ '${{ inputs.require-validate }}' == 'true' ]] && [[ '${{ steps.validate.outputs.validate-outcome }}' == 'failure' ]]; then
          echo ${{ steps.validate.outputs.stdout }}
          echo ${{ steps.validate.outputs.stderr }}
          exit 1
        fi

    - name: Terraform Plan Status
      shell: bash
      run: |
        if [[ '${{ steps.plan.outputs.plan-outcome }}' == 'failure' ]]; then
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          exit 1
        fi

#     - name: Terraform Format Status
#       shell: bash
#       run: |
#         if [[ '${{ inputs.require-formatting }}' == 'true' ]] && [[ '${{ steps.fmt.outputs.fmt-outcome }}' == 'failure' ]]; then
#           echo ${{ steps.fmt.outputs.stdout }}
#           echo ${{ steps.fmt.outputs.stderr }}
#           exit 1
#         fi
# 
#     - name: Terraform Apply
#       shell: bash
#       run: |
#         if [[ '${{ github.ref }}' != 'refs/heads/${{ inputs.apply-branch }}' ]]
#         then
#           echo
#           echo
#           echo "********"
#           echo "Branch is not '${{ inputs.apply-branch }}', 'terraform apply' will not be executed."
#           echo "********"
#           echo
#           exit 0
#         fi

#         # Update remote references
#         git fetch --quiet

#         if [[ "$(git rev-parse origin/${{ github.ref_name }})" != "$(git rev-parse HEAD)" ]]
#         then
#           echo
#           echo
#           echo "********"
#           echo "Branch '${{ inputs.apply-branch }}' is not up to date, 'terraform apply' will not be executed."
#           echo "Please run only run this action on the latest commit on the '${{ inputs.apply-branch }}' branch."
#           echo "********"
#           echo
#           exit 1
#         fi

#         cd ${{ inputs.path }}
#         terraform apply -auto-approve
